baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "aether"

DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    title = "my new hugo il8n site"
    languageName = "English"
    contentDir = "content/english"
    weight = 2
  [languages.fr]
    title = "Ma nouveau site hugo internationalis√©e"
    languageName = "French"
    contentDir = "content/french"
    weight = 1
    
    
